### ISSUE TITLE
勘误

### ISSUE THREAD

**Issue by uchidasann** [wolverinn/Waking-Up#21]
操作系统那一节里，有关信号量的描述：
信号量(Semaphore)：初始化操作、P操作、V操作；P操作：信号量-1，检测是否小于0，小于则进程进入阻塞状态；V操作：信号量+1，**若小于等于0**，则从队列中唤醒一个等待的进程进入就绪态
小于等于应该改成大于等于吧?

**Comment by wolverinn** [comment]
是的

**Comment by dreamerlzl** [comment]
我觉得就是小于等于。

考虑以下简单情形：
1. 信号量初始化为1
2.第一个线程A进行P操作，信号量变为0，A没有被阻塞；
3.第二个线程B进行P操作，信号量变为-1，B被阻塞；
4.第三个线程C进行P操作，信号量变为-2，C被阻塞；
4.A进行V操作，信号量变为-1，此时应该唤醒B或C中的一个。

实际上， Operating System Internals and Design Principle 第7版这么写的：
1. A semaphore may be initialized to a nonnegative integer value.
2. The `semWait` operation decrements the semaphore value. If the value becomes negative, then the process executing the semWait is blocked. Otherwise, the process continues execution.
3. The `semSignal` operation increments the semaphore value. If the resulting value is less than or equal to zero, then a process blocked by a semWait operation, if any, is unblocked.

**Comment by uchidasann** [comment]
嗯嗯，你这么解释一下我就明白了。之前我理解的有问题😭。麻烦 @wolverinn 把内容再改回来吧，实在是不好意思
